### ISSUE TITLE
Critical warnings during fixtures load

### ISSUE THREAD

**Issue by PouleR** [floriansemm/SolrBundle#126]
Since the addition of some log statements we see a lot critical warnings during loading of our fixtures:

    solr.CRITICAL: no declaration for document found in entity <entity>

Not all our entities have the Solr\Document() annotation but they are processed in the EntityIndexerSubscriber.php

A solution could be to change to log level, or do you see other solutions?

**Comment by floriansemm** [comment]
there is no way to avoid this error because the subscriber can not decide between indexing during fixtures:load and normal indexing with persist and flush. This means the subscriber can not decide when to throw an exception or not.

You can run `doctrine:fixtures:load -V` to make your console output less verbose. You can also log the solr channel in a different file.

See: http://symfony.com/doc/current/cookbook/logging/channels_handlers.html#switching-a-channel-to-a-different-handler

**Comment by PouleR** [comment]
Thanks for the idea, we will change our monolog settings for the solr channel.
