### ISSUE TITLE
Base Class private properties are not read by AnnotationReader

### ISSUE THREAD

**Issue by rajasaur** [floriansemm/SolrBundle#89]
I have a setup where my BaseEntity contains some private properties that Id like to index. With the current setup, AnnotationReader seems to be doing
```
   $reflectionClass = new \ReflectionClass($entity);
   $properties = $reflectionClass->getProperties();
```
which only picks up protected and public fields from base class. Can this be updated to pick up private properties from the base class if they are annotated with @Solr\Field. 

The only way I have right now to access that field via solr is to change the visibility level of my field in Base class to protected or public.

**Comment by marci** [comment]
The fix in commit 8e7b8928a6aa316e7e98bb13ab12616989e2e627 is actually causing bad behaviour. Calling getProperties() on main class results in retrieving all public/protected properties *including* inherited properties and calling getProperties on parent class retrieves some of these properties too. The problem is with merging of properties retrieved from current and parent classes. Method getProperties() actually returns only numerically indexed array of ReflectionProperty classes (not indexed by property names), so the identical properties are not really replaced but only appended to the resulting array - so now I have some of the properties fields duplicated, that results in incorrect behaviour ("multiple values encountered for non multiValued field").

Also, this fix for receiving private properties can only work with one parent class, it should be probably written to traverse all parent classes recursively.


Simple example:

```php
// properties retrieved from this class will be 'someProperty' and 'someOtherProperty'
/** @Solr\Document(repo="A") */
class A extends B { }

// properties retrieved from this class will be 'someProperty' and 'someOtherProperty'
class B extend C { 
   /** @Solr\Field **/
   protected $someProperty;
}

// this class won't be visited directly (the private property won't be retrieved)
class C {
   /** @Solr\Field **/
   protected $someOtherProperty;
   private $somePrivateProperty; 
}
```

So parsing class A will result in 4 fields definition: and  'someProperty' ,  'someProperty' , 'someOtherProperty', 'someOtherProperty' as array_merge won't get rid of the duplicates

**Comment by floriansemm** [comment]
@marci I it think I have fixed this issue now. Thanks for your hint.

**Comment by marci** [comment]
I can't really test it as I already switched to elastic search, but I think you have still issue here:
```
return array_merge($reflectionClass->getProperties(), $this->getParentProperties($parent));
```
$reflectionClass->getProperties() will get you public, protected and private properties defined in that concrete class BUT ALSO all inherited public and protected properties from parent classes. So calling $this->getParentProperties($parent) will then get you some of these properties too. You assume that array_merge will get rid of these duplicates, but it won't. See my last example with comment bellow.

**Comment by floriansemm** [comment]
@marci I fixed this issue with https://github.com/floriansemm/SolrBundle/blob/master/Doctrine/Annotation/AnnotationReader.php#L234
